apiVersion: v1
kind: Service
metadata:
  name: fastapi-app-service
spec:
  selector:
    app: fastapi-test-okr-app
  ports:
  - protocol: "TCP"
    port: 8000
    targetPort: 8000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-test-okr-app
spec:
  selector:
    matchLabels:
      app: fastapi-test-okr-app
  replicas: 3
  template:
    metadata:
      labels:
        app: fastapi-test-okr-app
    spec:
      containers:
      - name: fastapi-test-okr-app
        image: fastapi_okrapp_kubernetes:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000